#pragma once

// From ORBE3.h

#define ORBE_MOUSE_BUTTON_1         0
#define ORBE_MOUSE_BUTTON_2         1
#define ORBE_MOUSE_BUTTON_3         2
#define ORBE_MOUSE_BUTTON_4         3
#define ORBE_MOUSE_BUTTON_5         4
#define ORBE_MOUSE_BUTTON_6         5
#define ORBE_MOUSE_BUTTON_7         6
#define ORBE_MOUSE_BUTTON_8         7
#define ORBE_MOUSE_BUTTON_LAST      ORBE_MOUSE_BUTTON_8
#define ORBE_MOUSE_BUTTON_LEFT      ORBE_MOUSE_BUTTON_1
#define ORBE_MOUSE_BUTTON_RIGHT     ORBE_MOUSE_BUTTON_2
#define ORBE_MOUSE_BUTTON_MIDDLE    ORBE_MOUSE_BUTTON_3